### ISSUE TITLE
App Crash on Android 6 with no permissions given

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/random-contact#1]
The current version of the app is crashing on Android 6 (M) with the below error when no permission is given in system settings.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ae.apps.randomcontact/com.ae.apps.randomcontact.MainActivity}: java.lang.IllegalArgumentException: n <= 0: 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.IllegalArgumentException: n <= 0: 0
	at java.util.Random.nextInt(Random.java:182)
	at com.ae.apps.randomcontact.c.c.<init>(Unknown Source)
	at com.ae.apps.randomcontact.MainActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6245)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	... 9 more

**Comment by midhunhk** [comment]
Added code to fix this issue. Will be available in the next public release.
