### ISSUE TITLE
WhatsApp Integration

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/random-contact#5]
Allow to chat with a Contact using WhtasApp if it is installed.

- [x] Show a WhatsApp button next to a contact number if WhatsApp is installed
- [x] Open the WhatsApp chat with the contact that was clicked
  - [x] Handle if number is not associated with a WhatsApp account
  - [x] Handle if WhatsApp cannot process the selected contact

-----
### Method 1 Into Conversation
- https://faq.whatsapp.com/en/android/28000012
- https://stackoverflow.com/questions/15462874/sending-message-through-whatsapp
- https://stackoverflow.com/questions/19081654/send-text-to-specific-contact-programmatically-whatsapp
### Method 2 Into a chat
- https://stackoverflow.com/questions/19339150/send-message-to-specific-contact-through-whatsapp-from-another-app?noredirect=1&lq=1
### Method 3 With ContactId
- https://stackoverflow.com/questions/19081654/send-text-to-specific-contact-programmatically-whatsapp

**Comment by midhunhk** [comment]
https://stackoverflow.com/questions/6284011/start-whatsapp-with-android-content-intent-action-sendto

**Comment by midhunhk** [comment]
Process: com.ae.apps.randomcontact, PID: 24844
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SENDTO typ=text/plain pkg=com.whatsapp (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1872)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1568)
        at android.app.Activity.startActivityForResult(Activity.java:3755)
        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
        at android.app.Activity.startActivityForResult(Activity.java:3716)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
        at android.app.Activity.startActivity(Activity.java:4036)
        at android.app.Activity.startActivity(Activity.java:3998)
        at com.ae.apps.randomcontact.utils.Utils.sendWhatsAppMessage(Utils.java:92)

**Comment by midhunhk** [comment]
Looks like ACTION_SENDTO a phone number is not supported by WhatsApp. 

https://stackoverflow.com/questions/6284011/start-whatsapp-with-android-content-intent-action-sendto
